; Sample "log4rexx.properties" file, Rony G. Flatscher, 2007-04-11
;
; a simple 'log4rexx' sample configuration file
;
; - entries are strings in the form: key=value
;   attention: case of key is irrelevant (as in Rexx everything gets translated to uppercase)
;
; - empty lines or lines starting with ';' or '#' or '!' or '--' are ignored
;
; - these are the defined logLevels: TRACE < DEBUG < INFO < WARN < ERROR < FATAL
;   just send messages of one of those logLevel names to a logger
;
; - anytime you need a logger, get it by querying the ".LogManager", e.g.:
;
;      aLogger=.LogManager~getLogger("rootLogger") -- get the rootLogger
;
;   then send a log message, e.g.:
;
;      aLogger~trace("This is a trace message")
;      aLogger~debug("This is a debug message")
;      aLogger~info("This is an info message")
;      aLogger~warn("A condition got raised!", condition('O'))
;      aLogger~error("This is an error message")
;      aLogger~fatal("This is a fatal (error) message")


# ======================================================================================
; turn on 'log4rexx' framework debugging:
# log4rexx.config.LogLog.debug=1
;
; turn even logging of framework warnings and errors off:
# log4rexx.config.LogLog.quietMode=1
;
# ======================================================================================


# ====================== define and configure loggers
# ---------------------- logger named "rootLogger" (this logger is always available)
;
-- name of the following logger: "rootLogger"
; send logs at level "DEBUG" or higher to to appender named "DEST_APP1"
log4rexx.logger.rootLogger = debug, dest_app1


# ---------------------- logger named "rgf.sockets" (meant to serve 'rgf.sockets.cls' module)
;
; send logs at level "TRACE" or higher to to appender named "RGF_APP1" and "RGF_APP2"
-- name of the following logger: "RGF.SOCKETS"
; log4rexx.logger.RGF.SOCKETS           = debug, rgf_app1, rgf_app2
log4rexx.logger.RGF.SOCKETS           = debug, rgf_app2, rgf_app2_2
;
; if 'additivity' is .true (default), then log messages are sent to "inherited" appenders as well
# log4rexx.logger.rgf.sockets.additivity=false



# ====================== define and configure appenders
; ---------------------- appender named "DEST_APP1"
log4rexx.appender.DEST_APP1               =ConsoleAppender
# log4rexx.appender.dest_app1.filter      = filter(list)
log4rexx.appender.dest_app1.ImmediateFlush=true
log4rexx.appender.dest_app1.layout        =pat_layout1
log4rexx.appender.dest_app1.Target        =stderr


; ---------------------- appender named "RGF_APP1"
log4rexx.appender.RGF_APP1                =ConsoleAppender
log4rexx.appender.rgf_app1.filter         =weekDays,workingHours
log4rexx.appender.rgf_app1.ImmediateFlush =1
log4rexx.appender.rgf_app1.layout         =pat_layout1
log4rexx.appender.rgf_app1.Target         =.error


; ---------------------- appender named "RGF_APP2"
log4rexx.appender.RGF_APP2                = FileAppender
;log4rexx.appender.rgf_app2.filter         = weekDays,workingHours
log4rexx.appender.rgf_app2.layout         = html_layout1
log4rexx.appender.rgf_app2.fileName       = rgf_app2_appender.html
log4rexx.appender.rgf_app2.append         = false
log4rexx.appender.rgf_app2.bufferedIO     = true

; ---------------------- appender named "RGF_APP2_2"
log4rexx.appender.RGF_APP2_2                = FileAppender
log4rexx.appender.rgf_app2_2.layout         = html_layout2
log4rexx.appender.rgf_app2_2.fileName       = rgf_app2-2_ext_output.html
log4rexx.appender.rgf_app2_2.append         = false
log4rexx.appender.rgf_app2_2.bufferedIO     = true

; ---------------------- appender named "RGF_APP3"
log4rexx.appender.RGF_APP3                = TelnetAppender
log4rexx.appender.rgf_app3.layout         = pat_layout1
log4rexx.appender.rgf_app3.maxLogsInQueue = 50
;
; ignore all logs up to and including level 'TRACE'
log4rexx.appender.rgf_app3.Threshold      = trace




# ====================== define and configure layouts
; ---------------------- layout named "PAT_LAYOUT1"
log4rexx.layout.PAT_LAYOUT1           =PatternLayout
log4rexx.layout.pat_layout1.conversionPattern=%5N: %r [%c] %-5p - %m%n

; ---------------------- layout named "HTML_LAYOUT1"
log4rexx.layout.HTML_LAYOUT1          =HTMLLayout
log4rexx.layout.html_layout2.title    =Standard Infos (HTML_LAYOUT1)
log4rexx.layout.html_layout1.conversionPattern=%5N: %r [%c] %-5p - %m%n

; ---------------------- layout named "HTML_LAYOUT2"
log4rexx.layout.HTML_LAYOUT2          =HTMLLayout
log4rexx.layout.html_layout2.title    =Extended Infos (HTML_LAYOUT2)
log4rexx.layout.html_layout2.conversionPattern=%5N: %d{DS-} %d{TL}%c  %-5p %r %a  %m %n




# ====================== define and configure filters
; ---------------------- filter named "WEEKDAYS"
log4rexx.filter.WEEKDAYS              =WeekdayRangeFilter
log4rexx.filter.weekdays.weekdayMin   =Monday
log4rexx.filter.weekdays.weekdayMax   =Friday
log4rexx.filter.weekdays.acceptOnMatch=true

; ---------------------- filter named "WEEKEND"
log4rexx.filter.WEEKEND               =WeekdayRangeFilter
log4rexx.filter.weekend.weekdayMin    =Monday
log4rexx.filter.weekend.weekdayMax    =Friday
log4rexx.filter.weekend.acceptOnMatch =false

; ---------------------- filter named "WORKINGHOURS"
log4rexx.filter.WORKINGHOURS          =TimeRangeFilter
log4rexx.filter.workinghours.timeMin  =08:00
log4rexx.filter.workinghours.timeMax  =18:00
log4rexx.filter.workinghours.acceptOnMatch=true


