; 2007-01-11, ---rgf, a "simplelog.properties" file, gets processed by the "SimpleLog" class and
;             entries are strings in the form: key=value
;             empty lines or lines starting with ';' or '#' are ignored


# ======================================================================================
; turn on 'log4rexx' framework debugging:
# log4rexx.config.LogLog.debug=1
;
; turn even logging of framework warnings and errors off:
# log4rexx.config.LogLog.quietMode=1
;
# ======================================================================================


# ======================================================================================
# ====================== define defaults for 'SimpleLog' loggers

; 'showDateTime',  values: 1 | [.]true or 0 [.]false
log4rexx.config.simplelog.showDateTime = 0

; 'showLogName',   values: 1 | [.]true or 0 [.]false
log4rexx.config.simplelog.showLoggerName = 0

; 'showShortName', values: 1 | [.]true or 0 [.]false
log4rexx.config.simplelog.showShortName = 0

; 'defaultLog', possible values: ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
log4rexx.config.simplelog.defaultLogLevel = WARN


# ======================================================================================
# ====================== define 'SimpleLog' loggers

; 'logLevel' defaults to "INFO", values: ALL < TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF
;
; 'logLevel': log messages starting at the following level will be processed:
-- name of the following logger: "a_simple_logger_1"
log4rexx.logger.a_simple_logger_1                =

-- name of the following logger: "a_simple_logger_2"
log4rexx.logger.a_simple_logger_2                = warn
log4rexx.logger.a_simple_logger_2.showDateTime   = true
log4rexx.logger.a_simple_logger_2.showLoggerName = false
log4rexx.logger.a_simple_logger_2.showShortName  = true

-- name of the following logger: "a.simple.logger.3"
log4rexx.logger.a.simple.logger.3                = error
log4rexx.logger.a.simple.logger.3.showDateTime   = true
log4rexx.logger.a.simple.logger.3.showLoggerName = true
log4rexx.logger.a.simple.logger.3.showShortName  = true


